### ISSUE TITLE
Local catalog targeting local json schemas

### ISSUE THREAD

**Issue by nvuillam** [chris48s/v8r#110]
Would it be possible to manage that local catalog files can refer to local JSON schema files ?

cf https://github.com/nvuillam/mega-linter/issues/730#issuecomment-918898173

Many thanks !

**Comment by chris48s** [comment]
This did come up when the catalogs feature was implemented and we had a bit of a discussion around it:

https://github.com/chris48s/v8r/pull/92#discussion_r671888584

Long story short: the `url` property is "An absolute URL to the schema location" by design for several reasons

- We can validate custom catalogs against https://json.schemastore.org/schema-catalog.json
- If a custom catalog were to include a relative path, it may be ambiguous what the path is relative to if the custom catalog is local, and completely nonsensical if the custom catalog is remote

Obviously a local schema can be supplied on a one-off basis using the `--schema` flag but there is no way to specify a local schema in a custom catalog and I don't think that is the right place to add it.

---

One thing I have been mulling over since merging #92 is maybe v8r should have some kind of bespoke project config file (a `.v8rrc` or something) which is explicitly _not_ a schema catalog (although it would probably end up being an extension of https://json.schemastore.org/schema-catalog.json ) that does allow local schema paths. If

- `.v8rrc` must be a local file and
- `v8r` looks for `.v8rrc` in the directory it is invoked from

then that would clear up the issue of where relative paths are relative to. It could also store files to ignore and that sort of thing if I implement #21. Of course, then I have to design and maintain a custom file format for it including validation. I don't think this is something I will work on soon. It needs some thought before I commit to it, but it is slowly churning around in my mind..

**Comment by nvuillam** [comment]
Local [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)-like file would indeed be nice , please let me know if you decide to implement it :)

**Comment by chris48s** [comment]
Config file format added in v0.12.0 includes a `customCatalog` property which can include references to local schemas as well as remote ones. Docs at https://github.com/chris48s/v8r#configuration
