### ISSUE TITLE
Embedding v8r in Mega-Linter ?

### ISSUE THREAD

**Issue by nvuillam** [chris48s/v8r#3]
Your repo seems great but it does not seems very used yet ( according to downloads number in https://www.npmjs.com/package/v8r )

Is it stable enough so I can include it in Mega-Linter without risks ? :)

If yes:
- it would be nice to have an option `--ignore-schema-not-found` to make **No suitable schema could be found** return 0 anyway
- Add some cache management to avoid downloading schemas catalog for each v8r call

https://nvuillam.github.io/mega-linter/

Thanks !

**Comment by chris48s** [comment]
Hello. Thanks for your interest in the project. I think the short answer to your question is: Not yet.

To give a longer answer:

As you've noticed, this project is not widely used. Tbh, I suspect I am probably the only person really using it, but I like to document stuff as I go along :) It is useful to get some feedback on the project but there are still some rough edges and I probably wouldn't want to dump it into lots of CI builds just yet.

To give a bit more detail on the rough edges:

- External references: As noted in #2, at the moment if a schema references another schema, the reference is not resolved. e.g: `echo '{}' > foo.json && npx v8r foo.json -s https://json.schemastore.org/grunt-clean-task`. Practically, this prevents a non-trivial subset of the schemas on schemastore.org from being useful and should be a fix-able issue.

- There are a some schemas in schemastore which throw some kind of error trying to use them. The reasons for this vary so these are slightly difficult to reason about as a group, but to give three examples:
    - `touch foo.yml && npx v8r foo.yml -s https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json`: This fails because the schema is defined using a draft of the JSON Schema spec that AJV is not (yet) compatible with.
    - `echo '{}' > foo.json && npx v8r foo.json -s https://json.schemastore.org/packer`: This fails because the first line of the schema is `"$schema": "https://json-schema.org/draft-07/schema#"` not `"$schema": "https://json-schema.org/draft-07/schema#"` which is strictly invalid (see https://json-schema.org/understanding-json-schema/reference/schema.html ) but I suspect some validation libraries do accept it as a use-able schema.
    - `touch foo.yml && npx v8r foo.yml -s https://json.schemastore.org/ansible-role-2.9`: I couldn't begin to tell you what is wrong in this case.

    The upshot of all this is there are a non-zero number of situations in which a suitable schema for the input file does exist in schemastore but then the validation fails for a reason other than the input file is invalid. I don't plan to attempt to fix or address these issues in this project - the objective is to be a fairly thin layer of glue between AJV and schemastore. JSONSchema is a murky world and I think its inevitable there will not always be 100% compatibility, especially as the JSONSchema spec and Schemastore evolve over time. That said, your use-case is interesting :) So far my use-case has been "I know what I'm trying to validate, but I want to outsource the job of maintaining schemas to a registry" whereas I guess yours is more like "Here's a bag of files. Lets see if we can find a schema to validate any of them". I think your suggestion of a flag or mode that treats "we couldn't find a schema" as a success (or at least not a failure) could be expanded to also consider "we did find a schema but couldn't validate the input file with it [for reasons you don't care about]" as not a failure. That would probably be a way to smooth a lot of that messiness over for a situation where validating against a schema is a value-add as opposed to a hard requirement.

- Globs and paths: As noted in #1 (and #4 )only exact filenames are matched. Matching paths and glob patterns too would be a big improvement and auto-detect suitable schemas in many more cases.

All of that said, the majority of schemas on schemastore do work with AJV and this tool is quite useful in its current form. Mainly because most of the heavy lifting is done by AJV and schemastore. I have a bit of time free between Christmas and New Year and ideally I'd like to use some of it to tackle the above problems. I'll keep you posted.

**Comment by nvuillam** [comment]
Taanks a lot for your detailed answer :)

v8r is not adopted probably because its best use... is in CI, and having to browse files before calling it makes it too long to setup in a project

But in Mega-Linter I clearly see an interest to be able to detect schema errors (that may avoid hours of debugging in some cases).
It's ok if not all cases work, even if "most of them" are working it would already be a great addition, but to do that I would need at least:
- Have a way to return 0 code when the schema is not found ,with an additional option `--ignore-no-schema`
- Have a way to return 0 code when schema contains an error or is not supported, with an additioan option `ignore-schema-not-supported`

For the second point, do you have an idea about how v8r could detect a not supported schema ?

I already made a [draft PR](https://github.com/nvuillam/mega-linter/pull/176) embedding v8r, and besides the point I listed it's ready to be added 
 
Are you open to incoming PRs ? If yes, I may submit one someday (and add Mega-Linter to this repo to see if you let some mistakes haha )

**Comment by chris48s** [comment]
I've just released [0.2.0](https://www.npmjs.com/package/v8r/v/0.2.0) which adds the ability to find schemas using paths and glob patterns and adds a `--ignore-errors` flag (see https://github.com/chris48s/v8r#exit-codes ).

Re-reading this thread I notice you edited the top post to mention caching the schema catalog (which I overlooked the first time). That's an interesting topic so I've made a new issue for that: https://github.com/chris48s/v8r/issues/13

I'm going to close this issue now as I think everything outstanding is covered in other issues. I'll continue to pick at these as I have some time over the next week or so. If you want to pick any up and submit a PR, post in the issue first as I don't want us to duplicate the same work.

**Comment by nvuillam** [comment]
Thanks a lot for your reactivity :)

**Comment by nvuillam** [comment]
@chris48s  I'm glad to announce you that now v8r is officially a member of Mega-Linter :)

- https://nvuillam.github.io/mega-linter/descriptors/yaml_v8r/
- https://nvuillam.github.io/mega-linter/descriptors/yaml_v8r/

You can now stop using your package in command line and integrate it in CI jobs of your projects :)
