### ISSUE TITLE
fileMatch collision

### ISSUE THREAD

**Issue by gnawhleinad** [chris48s/v8r#61]
I'm not sure what the right :wrench: is... but I have a GitHub Action called `deploy.yaml` that isn't validated against the GitHub Action schema because the Deployer Recipe takes precedence.

Some potential fixes:

- https://github.com/chris48s/v8r/issues/17 which would allow me to define my own catalog and exclude Deployer Recipe
- new command line flag to ignore schema(s) (like Deployer Recipe)

**Comment by chris48s** [comment]
If you need to validate a file and the schema suggested by schemastore based on the file name isn't right you can use the `--schema` flag to specify the right one to use e.g:

```
v8r deploy.yaml --schema https://json.schemastore.org/github-action.json
```

**Comment by gnawhleinad** [comment]
> If you need to validate a file and the schema suggested by schemastore based on the file name isn't right you can use the `--schema` flag to specify the right one to use e.g:

:bow:, that's very helpful!

Unfortunately, it doesn't completely resolve my issue. For my use-case, I'm not using `v8r` directly but via https://github.com/nvuillam/mega-linter which (right now) only allows flag(s) for the entire run (of a project). In other words, if my project contains multiple YAML types... then `--schema` won't work since it will use the argument for _all_ the YAML files.

:point_up: doesn't mean that a fix / enhancement _needs_ to exist in `v8r` though...

**Comment by chris48s** [comment]
Yes - for the moment that behaviour of running v8r on every JSON/yaml file in your repo is a feature of mega-linter rather than a feature of v8r.

That said, an idea I am toying with (but haven't implemented yet) is the ability to run v8r on a directory or glob pattern (see https://github.com/chris48s/v8r/issues/21 ) so I guess at the point you can run something like `v8r directory/*.yml` to validate N different files against N different schemas, it probably then becomes necessary to be able to supply a user-defined mapping of which files to validate against which schemas.. which then starts to look a lot like #17 :thinking:

**Comment by ottumm** [comment]
Would it be possible to read the schema from a comment at the top of the file?

This wouldn't work for pure JSON, since it doesn't support comments, but it would work for YAML.
